# mysql datasource

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池 ： https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5

  # jpa 配置信息
  jpa:
    # 指定数据库类型
    database: MYSQL
    #显示sql语句
    show-sql: true
    hibernate:
    #该配置自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表，
      ddl-auto: update
      # 根据实体创建表/结构，自动指定命名策略
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

